base_images:
  base:
    name: "4.21"
    namespace: ocp
    tag: base
  ocp_builder_rhel-9-golang-1.22-openshift-4.17:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.22-openshift-4.17
binary_build_commands: make build --warn-undefined-variables
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.12
images:
- dockerfile_path: Dockerfile
  from: base
  inputs:
    ocp_builder_rhel-9-golang-1.22-openshift-4.17:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.17
  to: crd-schema-gen
promotion:
  to:
  - name: "4.21"
    namespace: ocp
releases:
  initial:
    integration:
      name: "4.21"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.21"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: "3"
      memory: 2Gi
test_binary_build_commands: make build GO_BUILD_FLAGS:='-race' --warn-undefined-variables
tests:
- as: verify
  commands: |
    go get -u golang.org/x/tools/imports
    make verify -k --warn-undefined-variables
  container:
    from: bin
zz_generated_metadata:
  branch: release-4.21
  org: openshift
  repo: crd-schema-gen
